//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.20 at 12:48:48 PM SGT 
//


package com.soap.consume.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="spmHeader" type="{http://msg.webservice.wms7.daifuku.co.jp/xsd}SPMHeader" minOccurs="0"/&gt;
 *         &lt;element name="spmDetail" type="{http://msg.webservice.wms7.daifuku.co.jp/xsd}SPMDetail" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "spmHeader",
    "spmDetail"
})
@XmlRootElement(name = "StoragePlanMessage", namespace = "http://server.webservice.wms7.daifuku.co.jp")
public class StoragePlanMessage {

    @XmlElementRef(name = "spmHeader", namespace = "http://server.webservice.wms7.daifuku.co.jp", type = JAXBElement.class, required = false)
    protected JAXBElement<SPMHeader> spmHeader;
    @XmlElement(namespace = "http://server.webservice.wms7.daifuku.co.jp", nillable = true)
    protected List<SPMDetail> spmDetail;

    /**
     * Gets the value of the spmHeader property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SPMHeader }{@code >}
     *     
     */
    public JAXBElement<SPMHeader> getSpmHeader() {
        return spmHeader;
    }

    /**
     * Sets the value of the spmHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SPMHeader }{@code >}
     *     
     */
    public void setSpmHeader(JAXBElement<SPMHeader> value) {
        this.spmHeader = value;
    }

    /**
     * Gets the value of the spmDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spmDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpmDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SPMDetail }
     * 
     * 
     */
    public List<SPMDetail> getSpmDetail() {
        if (spmDetail == null) {
            spmDetail = new ArrayList<SPMDetail>();
        }
        return this.spmDetail;
    }

}
