//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.20 at 12:48:48 PM SGT 
//


package com.soap.consume.stub;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WMS7Response complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WMS7Response"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="messageHeader" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *         &lt;element name="responseMessageHeader" type="{http://msg.webservice.wms7.daifuku.co.jp/xsd}ResponseMessageHeader" minOccurs="0"/&gt;
 *         &lt;element name="responseMessages" type="{http://msg.webservice.wms7.daifuku.co.jp/xsd}ResponseMessage" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WMS7Response", propOrder = {
    "messageHeader",
    "responseMessageHeader",
    "responseMessages"
})
public class WMS7Response {

    @XmlElementRef(name = "messageHeader", namespace = "http://msg.webservice.wms7.daifuku.co.jp/xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<Object> messageHeader;
    @XmlElementRef(name = "responseMessageHeader", namespace = "http://msg.webservice.wms7.daifuku.co.jp/xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ResponseMessageHeader> responseMessageHeader;
    @XmlElement(nillable = true)
    protected List<ResponseMessage> responseMessages;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public JAXBElement<Object> getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     
     */
    public void setMessageHeader(JAXBElement<Object> value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the responseMessageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ResponseMessageHeader }{@code >}
     *     
     */
    public JAXBElement<ResponseMessageHeader> getResponseMessageHeader() {
        return responseMessageHeader;
    }

    /**
     * Sets the value of the responseMessageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ResponseMessageHeader }{@code >}
     *     
     */
    public void setResponseMessageHeader(JAXBElement<ResponseMessageHeader> value) {
        this.responseMessageHeader = value;
    }

    /**
     * Gets the value of the responseMessages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the responseMessages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResponseMessages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResponseMessage }
     * 
     * 
     */
    public List<ResponseMessage> getResponseMessages() {
        if (responseMessages == null) {
            responseMessages = new ArrayList<ResponseMessage>();
        }
        return this.responseMessages;
    }

}
