//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.19 at 10:17:20 AM SGT 
//


package com.soap.produce.stub.difuku;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZwsStSrmRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZwsStSrmRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MessageHeader" type="{urn:sap-com:document:sap:soap:functions:mc-style}ZwsStMessageHeader"/&gt;
 *         &lt;element name="Srm" type="{urn:sap-com:document:sap:soap:functions:mc-style}ZwsTtSrm"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZwsStSrmRequest", propOrder = {
    "messageHeader",
    "srm"
})
public class ZwsStSrmRequest {

    @XmlElement(name = "MessageHeader", required = true)
    protected ZwsStMessageHeader messageHeader;
    @XmlElement(name = "Srm", required = true)
    protected ZwsTtSrm srm;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ZwsStMessageHeader }
     *     
     */
    public ZwsStMessageHeader getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZwsStMessageHeader }
     *     
     */
    public void setMessageHeader(ZwsStMessageHeader value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the srm property.
     * 
     * @return
     *     possible object is
     *     {@link ZwsTtSrm }
     *     
     */
    public ZwsTtSrm getSrm() {
        return srm;
    }

    /**
     * Sets the value of the srm property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZwsTtSrm }
     *     
     */
    public void setSrm(ZwsTtSrm value) {
        this.srm = value;
    }

}
