//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.17 at 02:48:21 PM SGT 
//


package com.soap.produce.stub;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.soap.produce.stub package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.soap.produce.stub
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZStorageResultMessage }
     * 
     */
    public ZStorageResultMessage createZStorageResultMessage() {
        return new ZStorageResultMessage();
    }

    /**
     * Create an instance of {@link ZwsStSrmRequest }
     * 
     */
    public ZwsStSrmRequest createZwsStSrmRequest() {
        return new ZwsStSrmRequest();
    }

    /**
     * Create an instance of {@link ZStorageResultMessageResponse }
     * 
     */
    public ZStorageResultMessageResponse createZStorageResultMessageResponse() {
        return new ZStorageResultMessageResponse();
    }

    /**
     * Create an instance of {@link ZwsStSrmResponse }
     * 
     */
    public ZwsStSrmResponse createZwsStSrmResponse() {
        return new ZwsStSrmResponse();
    }

    /**
     * Create an instance of {@link ZwsStSrm }
     * 
     */
    public ZwsStSrm createZwsStSrm() {
        return new ZwsStSrm();
    }

    /**
     * Create an instance of {@link ZwsStMessageHeader }
     * 
     */
    public ZwsStMessageHeader createZwsStMessageHeader() {
        return new ZwsStMessageHeader();
    }

    /**
     * Create an instance of {@link ZwsStResponseMessageHeader }
     * 
     */
    public ZwsStResponseMessageHeader createZwsStResponseMessageHeader() {
        return new ZwsStResponseMessageHeader();
    }

    /**
     * Create an instance of {@link ZwsStResultMessageHeader }
     * 
     */
    public ZwsStResultMessageHeader createZwsStResultMessageHeader() {
        return new ZwsStResultMessageHeader();
    }

    /**
     * Create an instance of {@link ZwsStResponseMessage }
     * 
     */
    public ZwsStResponseMessage createZwsStResponseMessage() {
        return new ZwsStResponseMessage();
    }

    /**
     * Create an instance of {@link ZwsTtSrm }
     * 
     */
    public ZwsTtSrm createZwsTtSrm() {
        return new ZwsTtSrm();
    }

    /**
     * Create an instance of {@link ZwsTtResponseMessage }
     * 
     */
    public ZwsTtResponseMessage createZwsTtResponseMessage() {
        return new ZwsTtResponseMessage();
    }

}
