//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.17 at 02:48:21 PM SGT 
//


package com.soap.produce.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ZwsStSrmResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZwsStSrmResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MessageHeader" type="{urn:sap-com:document:sap:soap:functions:mc-style}ZwsStResultMessageHeader"/&gt;
 *         &lt;element name="ResponseMessageHeader" type="{urn:sap-com:document:sap:soap:functions:mc-style}ZwsStResponseMessageHeader"/&gt;
 *         &lt;element name="ResponseMessage" type="{urn:sap-com:document:sap:soap:functions:mc-style}ZwsTtResponseMessage"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZwsStSrmResponse", propOrder = {
    "messageHeader",
    "responseMessageHeader",
    "responseMessage"
})
public class ZwsStSrmResponse {

    @XmlElement(name = "MessageHeader", required = true)
    protected ZwsStResultMessageHeader messageHeader;
    @XmlElement(name = "ResponseMessageHeader", required = true)
    protected ZwsStResponseMessageHeader responseMessageHeader;
    @XmlElement(name = "ResponseMessage", required = true)
    protected ZwsTtResponseMessage responseMessage;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ZwsStResultMessageHeader }
     *     
     */
    public ZwsStResultMessageHeader getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZwsStResultMessageHeader }
     *     
     */
    public void setMessageHeader(ZwsStResultMessageHeader value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the responseMessageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ZwsStResponseMessageHeader }
     *     
     */
    public ZwsStResponseMessageHeader getResponseMessageHeader() {
        return responseMessageHeader;
    }

    /**
     * Sets the value of the responseMessageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZwsStResponseMessageHeader }
     *     
     */
    public void setResponseMessageHeader(ZwsStResponseMessageHeader value) {
        this.responseMessageHeader = value;
    }

    /**
     * Gets the value of the responseMessage property.
     * 
     * @return
     *     possible object is
     *     {@link ZwsTtResponseMessage }
     *     
     */
    public ZwsTtResponseMessage getResponseMessage() {
        return responseMessage;
    }

    /**
     * Sets the value of the responseMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZwsTtResponseMessage }
     *     
     */
    public void setResponseMessage(ZwsTtResponseMessage value) {
        this.responseMessage = value;
    }

}
