//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.17 at 02:48:21 PM SGT 
//


package com.soap.produce.stub;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ZwsStSrm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZwsStSrm"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Sequence" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="SapDocumentLineNo" type="{urn:sap-com:document:sap:rfc:functions}string"/&gt;
 *         &lt;element name="HU" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="ItemCode" type="{urn:sap-com:document:sap:rfc:functions}string"/&gt;
 *         &lt;element name="ResultQty" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Uom" type="{urn:sap-com:document:sap:rfc:functions}string"/&gt;
 *         &lt;element name="UserId" type="{urn:sap-com:document:sap:rfc:functions}string"/&gt;
 *         &lt;element name="ResultDate" type="{urn:sap-com:document:sap:rfc:functions}date10"/&gt;
 *         &lt;element name="ResultTime" type="{urn:sap-com:document:sap:rfc:functions}time"/&gt;
 *         &lt;element name="LocationNo" type="{urn:sap-com:document:sap:rfc:functions}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZwsStSrm", propOrder = {
    "sequence",
    "sapDocumentLineNo",
    "hu",
    "itemCode",
    "resultQty",
    "uom",
    "userId",
    "resultDate",
    "resultTime",
    "locationNo"
})
public class ZwsStSrm {

    @XmlElement(name = "Sequence")
    protected int sequence;
    @XmlElement(name = "SapDocumentLineNo", required = true)
    protected String sapDocumentLineNo;
    @XmlElement(name = "HU")
    protected int hu;
    @XmlElement(name = "ItemCode", required = true)
    protected String itemCode;
    @XmlElement(name = "ResultQty")
    protected int resultQty;
    @XmlElement(name = "Uom", required = true)
    protected String uom;
    @XmlElement(name = "UserId", required = true)
    protected String userId;
    @XmlElement(name = "ResultDate", required = true)
    protected String resultDate;
    @XmlElement(name = "ResultTime", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar resultTime;
    @XmlElement(name = "LocationNo", required = true)
    protected String locationNo;

    /**
     * Gets the value of the sequence property.
     * 
     */
    public int getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     */
    public void setSequence(int value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the sapDocumentLineNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSapDocumentLineNo() {
        return sapDocumentLineNo;
    }

    /**
     * Sets the value of the sapDocumentLineNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSapDocumentLineNo(String value) {
        this.sapDocumentLineNo = value;
    }

    /**
     * Gets the value of the hu property.
     * 
     */
    public int getHU() {
        return hu;
    }

    /**
     * Sets the value of the hu property.
     * 
     */
    public void setHU(int value) {
        this.hu = value;
    }

    /**
     * Gets the value of the itemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemCode() {
        return itemCode;
    }

    /**
     * Sets the value of the itemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemCode(String value) {
        this.itemCode = value;
    }

    /**
     * Gets the value of the resultQty property.
     * 
     */
    public int getResultQty() {
        return resultQty;
    }

    /**
     * Sets the value of the resultQty property.
     * 
     */
    public void setResultQty(int value) {
        this.resultQty = value;
    }

    /**
     * Gets the value of the uom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUom() {
        return uom;
    }

    /**
     * Sets the value of the uom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUom(String value) {
        this.uom = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the resultDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultDate() {
        return resultDate;
    }

    /**
     * Sets the value of the resultDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultDate(String value) {
        this.resultDate = value;
    }

    /**
     * Gets the value of the resultTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getResultTime() {
        return resultTime;
    }

    /**
     * Sets the value of the resultTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setResultTime(XMLGregorianCalendar value) {
        this.resultTime = value;
    }

    /**
     * Gets the value of the locationNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationNo() {
        return locationNo;
    }

    /**
     * Sets the value of the locationNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationNo(String value) {
        this.locationNo = value;
    }

}
